# Generated by Django 3.2 on 2021-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='price',
            field=models.TextField(),
        ),
    ]
