# Generated by Django 3.2 on 2021-06-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_load_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
