# Generated by Django 3.2 on 2021-06-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_smstext_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstext',
            name='text',
            field=models.PositiveIntegerField(),
        ),
    ]
