# Generated by Django 3.2 on 2021-07-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_load_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
