# Generated by Django 3.2 on 2021-07-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_load_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
