# Generated by Django 3.2 on 2021-07-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_load_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
