# Generated by Django 3.2 on 2021-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='to',
            field=models.CharField(max_length=11),
        ),
    ]
