# Generated by Django 3.2 on 2021-07-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_phonenumber_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='to',
            new_name='my_phone',
        ),
    ]
